### ISSUE TITLE
NullPointerException for View.getX(), card offset to left and animation speed.

### ISSUE THREAD

**Issue by usernotnull** [HarinTrivedi/FABRevealMenu-master#10]
Hi, great library and thanks for sharing.

Here are a few things i noticed, if it'll help improve the app.
1. When I didn't set menuRes by xml it gave me an error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.View.getX()' on a null object reference
                      at com.hlab.fabrevealmenu.helper.ViewHelper.getSheetRevealCenterX(ViewHelper.java:159)
```
Above happens when I do a bindAncherView() with no menuRes by xml
To circumvent the above i just added a dummy menu, then programmatically change it as suitable.
Just getting a log.e: 
`E/PropertyValuesHolder: Couldn't find setter/getter for property degree with value type float
`
2. When I clicked on the FAB, situated on the bottom end of parent, the FAB didn't move, the card appeared about an inch to the left of the FAB and then grew and then made a circular reveal to show the menu items. I can't share my code, but I just implemented the FAB as shown in the wiki, a FAB and a FABRevealMenu below it, wrapped in coordinator layout (i also tried with RelativeLayout). Nothing in code except the fabMenu.bindAncherView(fab)

3. Would be nice to control the animation speed, if you can make a public setter method.

**Comment by HarinTrivedi** [comment]
There are three examples given in demo, with xml and with custom menu layout. Try to follow it, and let me know if you find any issue.
