### ISSUE TITLE
Some Error with Gradle

### ISSUE THREAD

**Issue by deshario** [HarinTrivedi/FABRevealMenu-master#2]
Fail to crunch file !
![fail](https://cloud.githubusercontent.com/assets/11426727/21641687/06e2f218-d2b0-11e6-8522-6ad3bc7be1bc.PNG)

**Comment by HarinTrivedi** [comment]
Hi, try to move your project in upper directory.
I had faced similar issue with google services library when path becomes longer to process.
If doesn't help I will find another solution.

**Comment by deshario** [comment]
Actually i had remove these 2 from gradle and now it works fine !

compile('com.github.ozodrukh:CircularReveal:1.3.1@aar'){
transitive = true;
}

ext {
    PUBLISH_GROUP_ID = 'com.hlab.fabrevealmenu'
    PUBLISH_ARTIFACT_ID = 'fab-reveal-menu'
    PUBLISH_VERSION = '1.0.1'
}
