### ISSUE TITLE
Detecting action when FAB is clicked and custom view is shown

### ISSUE THREAD

**Issue by albert0m** [HarinTrivedi/FABRevealMenu-master#21]
Is it possible to put an additional action when the fab button is clicked? adding a standard click listener doesn't work

```
content.bindAnchorView(button);
button.setOnClickListener(v -> myAction());
```

**Comment by HarinTrivedi** [comment]
No, it wont. As click event is only supposed to open the menu as it gets overridden in library.
Sorry!
