### ISSUE TITLE
Menù out of screen (BUG)

### ISSUE THREAD

**Issue by formattato** [HarinTrivedi/FABRevealMenu-master#24]
When the menu is open, and close the application, at the next restart the menu opens out of the screen.
it does not always happen

**Comment by MFlisar** [comment]
I see this sometimes happening as well... Looks like following for me (got the screenshots from one of my users). Left is with an unopened menu, right is with an opened menu.

![2018-02-12 11_13_49-photos](https://user-images.githubusercontent.com/2437726/36091938-dba332ce-0fe5-11e8-8da3-2f698fd07255.png)

**Comment by MFlisar** [comment]
I can't reproduce this myself, but I think it may be some edge case of laying out parent and sub view, so posting the calculation to the parent view may not be perfect.

Using the `GlobalLayoutListener` probably solves this, as I can't reproduce it myself I'm not sure if this really is the issue...

Pull request that shows what I mean is here: https://github.com/HarinTrivedi/FABRevealMenu-master/pull/26
