### ISSUE TITLE
Now showing option when we implement this in second activity

### ISSUE THREAD

**Issue by unknownsdeveloper** [HarinTrivedi/FABRevealMenu-master#27]
please suggest any workaround(it is woring fine when I use in First Activity)
First Activity
![screenshot_1520931345](https://user-images.githubusercontent.com/24203947/37331667-84af2bf2-26ca-11e8-845b-5c2a8f3e4a8a.png)
Second Activity
![screenshot_1520931350](https://user-images.githubusercontent.com/24203947/37331673-892f8442-26ca-11e8-9ee0-b8ca39d131f3.png)
![screenshot_1520931353](https://user-images.githubusercontent.com/24203947/37331679-8d0201a8-26ca-11e8-9635-b2cc0f3cdeb0.png)

**Comment by HarinTrivedi** [comment]
Hi, did you try the latest version **1.0.4**? Let me know if you are still facing the issue.
Thanks for reporting
