### ISSUE TITLE
Current library broked the assembly of my project

### ISSUE THREAD

**Issue by SergeyBurlaka** [HarinTrivedi/FABRevealMenu-master#28]
After received several times:
```

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

```
And no help clean project, no help rebuild. All Dex settings are there in my project.
Only help to clone my project from git newly.

I suspect in my troubles this library source code
Because as before it was all okay

**Comment by HarinTrivedi** [comment]
Can you please try latest version 1.0.4?
Also share your gradle configuration if possible. Thanks.
