### ISSUE TITLE
API 24 Onwards the Revelmenu not displayed in proper place. 

### ISSUE THREAD

**Issue by RajkumarRepo** [HarinTrivedi/FABRevealMenu-master#29]
Click the fab button Before the API 23 it was worked. the same function run in APi 24 and above the ARC Animation not position in prpoer place. The Reveal menu displays in bottom end of the right corner.

**Comment by HarinTrivedi** [comment]
Hi did you try latest source code / gradle version 1.0.4 ?
Please let me know if this issue exists in this version.

Thanks for mentioning.
