### ISSUE TITLE
Minimum Api Version is 21

### ISSUE THREAD

**Issue by chnouman** [HarinTrivedi/FABRevealMenu-master#31]
It should be 18 atleast

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.hlab.fabrevealmenu:fab-reveal-menu:1.0.4] D:\gradle\caches\transforms-1\files-1.1\fab-reveal-menu-1.0.4.aar\cfbe3134ff7dab05e863daea447b358f\AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.hlab.fabrevealmenu" to force usage (may lead to runtime failures)

**Comment by HarinTrivedi** [comment]
Hi @chnouman, please use older version 1.0.3 for support from api 16

**Comment by chnouman** [comment]
with 1.0.3 it was giving error dear.

**Comment by HarinTrivedi** [comment]
Hi, in latest version support for <21 is not available. So this library wont work for you buddy.
Sorry!!
