### ISSUE TITLE
Could not find method leftShift()

### ISSUE THREAD

**Issue by Yair0007** [HarinTrivedi/FABRevealMenu-master#38]
First run attempt of the demo project I get:

Where:
Script 'C:\Users\Yair\Downloads\FABRevealMenu-master-master\android-release-aar.gradle' line: 43

ERROR: Could not find method leftShift() for arguments [android_release_aar_8cr3ibtgoj1e26k7b1gqbduh1$_run_closure6@78577158] on task ':fabrevealmenu:generateRelease' of type org.gradle.api.DefaultTask.

**Comment by HarinTrivedi** [comment]
@Yair0007 Hi, Did you try with latest code, I recently updated configurations
