### ISSUE TITLE
How to unbind anchor view

### ISSUE THREAD

**Issue by satish-kumar-p** [HarinTrivedi/FABRevealMenu-master#4]
Hello,

I have a view pager with 3 fragments. In 1 fragment i have a requirement to display menu items on Fab click & its working properly. No  issue there.
In remaining 2 fragments also i have fab click but here i move to another activity.

The issue im facing is when i bind anchorview, its showing menu items in the remaining 2 fragments also.
How can i unbind anchorview, so that i will get simple fab click to move to another activity.

I tried fabmenu.bindanchorview(null); but its not working.

**Comment by HarinTrivedi** [comment]
Try to implement click listener for FAB when you move to 2nd fragment, and bind menu when you are in 1st fragment.

**Comment by satish-kumar-p** [comment]
Wow....Tanks a lot...Its working now :+1:
