### ISSUE TITLE
  Caused by: java.lang.StackOverflowError: stack size 8MB                                                        at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6546)                                                at android.view.ViewGroup.resetResolvedLayoutDirection(ViewGroup.java:6546)

### ISSUE THREAD

**Issue by leelei** [HarinTrivedi/FABRevealMenu-master#5]
`    <com.hlab.fabrevealmenu.view.FABRevealMenu
        android:id="@+id/fab_menu"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone"
        app:menuCustomView="@layout/list_item_single_text"
        app:showOverlay="true" />
`
list_item_single_text

`<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/txt_title"
    style="@style/SecondaryTextView"
    android:textSize="16sp"
    android:layout_width="match_parent"
    android:layout_height="48dp"
    android:gravity="center"
    android:paddingLeft="16dp"
    android:paddingRight="16dp"
    android:background="@drawable/card_item_selector_row"
    tools:text="1989-02-13"/>
`

**Comment by HarinTrivedi** [comment]
Issues is resolved, please checkout with new version 1.0.2.
