### ISSUE TITLE
Please update support library

### ISSUE THREAD

**Issue by Icarus-Xu** [HarinTrivedi/FABRevealMenu-master#9]
to latest 25.3.1

**Comment by Salman-Samian** [comment]
buildToolsVersion '25.0.2' is latest @icyicarus

**Comment by Icarus-Xu** [comment]
Uh I meaned 'com.android.support.....' packages, idk why in the log there
were errors like "multiple support library versions"

**Comment by HarinTrivedi** [comment]
I think it has been updated in last pull requests, try to take update from repository.
